#数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 666666
    #useUnicode=true&characterEncoding=utf8 : 设置编码方式
    #autoReconnect=true 如果连接失败重新连接
    #allowMultiQueries=true 1.可以在sql语句后携带分号，实现多语句执行。 2.可以执行批处理，同时发出多个SQL语句。
    #useSSL=false MySQL在高版本需要指明是否进行SSL连接
    url: jdbc:mysql://192.168.40.201:3306/tanhua?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false
  data:
    mongodb:
      uri: mongodb://192.168.40.201:27017/tanhua_mongo

#dubbo配置
dubbo:
  application:
    name: tanhua-dubbo-service
  registry:
    address: zookeeper://192.168.40.252:2181
  scan:
    base-packages: com.tanhua.dubbo.api
  provider:
    timeout: 60000
#Mybatis plus配置
mybatis-plus:
  global-config:
    db-config:
      table-prefix: tb_
      id-type: auto
#log日志
logging:
  level:
    root: info
    com:
      tanhua: debug
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %msg - %logger{15}%n\'
